version: '3.7'
services:
    nginx:
        build:
            context: docker/nginx
        ports:
            - "8081:80"
        volumes:
            - ./:/app
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: docker/php-fpm
        volumes:
            - ./:/app
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_ROOT_USER=root"
            - "MYSQL_PASSWORD=root"
            - "MYSQL_DATABASE=test"
        ports:
            - "33061:3306"